from sikuli import*
import TABFunction

def create_customfields():
    #Client custom section
    #-------------------------#
    type('p', KeyModifier.ALT)
    type('c')
    wait("Clientrameke-1.png", 30)
    #----date type-----#
    type('n', KeyModifier.ALT)
    type('d')
    wait(Pattern("hisisarequir.png").similar(0.86), 30)
    paste('Custom Date')
    wait(1)
    type(Key.ENTER)
    waitVanish("Usethisdialo-3.png")
    #-----hours type--------#
    type('n', KeyModifier.ALT)
    type('h')
    wait("Namehisisare.png", 30)
    paste('Custom Hours')
    wait(1)
    type(Key.ENTER)
    waitVanish("Namehisisare.png")
    #-----List type---------#
    type('n', KeyModifier.ALT)
    type('l')
    wait("Namehisisare.png", 30)
    paste('Custom List')
    wait(1)
    type('n', KeyModifier.ALT)
    onAppear("Name.png", paste('List Item'))
    type(Key.ENTER)
    waitVanish("Name.png")
    type(Key.ENTER)
    waitVanish("Usethisdialo-3.png")
    #-----money type--------#
    type('n', KeyModifier.ALT)
    type('m')
    wait("Namehisisare.png", 30)
    paste('Custom Money')
    wait(1)
    type(Key.ENTER)
    waitVanish("Namehisisare.png")
    #-----number------------#
    type('n', KeyModifier.ALT)
    type('n')
    wait("Namehisisare.png")
    paste('Custom Number')
    wait(1)
    type(Key.ENTER)
    waitVanish("Namehisisare.png")
    #-----percent-----------#
    type('n', KeyModifier.ALT)
    type('p')
    wait("Namehisisare.png", 30)
    paste('Custom Percent')
    wait(1)
    type(Key.ENTER)
    waitVanish("Namehisisare.png")
    #-----text--------------#
    type('n', KeyModifier.ALT)
    type('t' + Key.ENTER)
    wait("Namehisisare.png", 30)
    paste('Custom Text')
    wait(1)
    type(Key.ENTER)
    waitVanish("Namehisisare.png")
    #-----timekeeper--------#
    type('n', KeyModifier.ALT)
    type('tt' + Key.ENTER)
    wait("Namehisisare.png", 30)
    paste('Custom Timekeep')
    wait(1)
    type(Key.ENTER)
    waitVanish("Namehisisare.png")
    #------Assert changes exists---------#
    assert exists(Pattern("Group1NameCu.png").similar(0.88))
   



    
    #Timekeeper custom section
    #-------------------------#
    type(Key.F6)
    wait(Pattern("cnemlTimekee.png").similar(0.96))
    #----date type-----#
    type('n', KeyModifier.ALT)
    type('d')
    wait("Namehisisare.png", 30)
    paste('Custom Date')
    wait(1)
    type(Key.ENTER)
    waitVanish("Namehisisare.png")
    #-----hours type--------#
    type('n', KeyModifier.ALT)
    type('h')
    wait("Namehisisare.png", 30)
    paste('Custom Hours')
    wait(1)
    type(Key.ENTER)
    waitVanish("Namehisisare.png")
    #-----List type---------#
    type('n', KeyModifier.ALT)
    type('l')
    wait("Namehisisare.png", 30)
    paste('Custom List')
    wait(1)
    type('n', KeyModifier.ALT)
    onAppear("Name.png", paste('List Item'))
    type(Key.ENTER)
    waitVanish("Name.png")
    type(Key.ENTER)
    waitVanish("Namehisisare.png")
    #-----money type--------#
    type('n', KeyModifier.ALT)
    type('m')
    wait("Namehisisare.png", 30)
    paste('Custom Money')
    wait(1)
    type(Key.ENTER)
    waitVanish("Namehisisare.png")
    #-----number------------#
    type('n', KeyModifier.ALT)
    type('n')
    wait("Namehisisare.png", 30)
    paste('Custom Number')
    wait(1)
    type(Key.ENTER)
    waitVanish("Namehisisare.png")
    #-----percent-----------#
    type('n', KeyModifier.ALT)
    type('p')
    wait("Namehisisare.png", 30)
    paste('Custom Percent')
    wait(1)
    type(Key.ENTER)
    waitVanish("Namehisisare.png")
    #-----text--------------#
    type('n', KeyModifier.ALT)
    type('t' + Key.ENTER)
    wait("Namehisisare.png", 30)
    paste('Custom Text')
    wait(1)
    type(Key.ENTER)
    waitVanish("Namehisisare.png")
    assert exists(Pattern("ITypeIpateNa.png").similar(0.89))

    
    #Activity custom section
    #-------------------------#
    type(Key.F6)
    wait(Pattern("ClientTimeke.png").similar(0.96), 30)
  #----date type-----#
    type('n', KeyModifier.ALT)
    type('d')
    wait("Namehisisare.png", 30)
    paste('Custom Date')
    wait(1)
    type(Key.ENTER)
    waitVanish("Namehisisare.png")
    #-----hours type--------#
    type('n', KeyModifier.ALT)
    type('h')
    wait("Namehisisare.png", 30)
    paste('Custom Hours')
    wait(1)
    type(Key.ENTER)
    waitVanish("Namehisisare.png")
    #-----List type---------#
    type('n', KeyModifier.ALT)
    type('l')
    wait("Namehisisare.png", 30)
    paste('Custom List')
    wait(1)
    type('n', KeyModifier.ALT)
    onAppear("Name.png", paste('List Item'))
    type(Key.ENTER)
    waitVanish("Name.png")
    type(Key.ENTER)
    waitVanish("Namehisisare.png")
    #-----money type--------#
    type('n', KeyModifier.ALT)
    type('m')
    wait("Namehisisare.png", 30)
    paste('Custom Money')
    wait(1)
    type(Key.ENTER)
    waitVanish("Namehisisare.png")
    #-----number------------#
    type('n', KeyModifier.ALT)
    type('n')
    wait("Namehisisare.png", 30)
    paste('Custom Number')
    wait(1)
    type(Key.ENTER)
    waitVanish("Namehisisare.png")
    #-----percent-----------#
    type('n', KeyModifier.ALT)
    type('p')
    wait("Namehisisare.png", 30)
    paste('Custom Percent')
    wait(1)
    type(Key.ENTER)
    waitVanish("Namehisisare.png")
    #-----text--------------#
    type('n', KeyModifier.ALT)
    type('t' + Key.ENTER)
    wait("Namehisisare.png", 30)
    paste('Custom Text')
    wait(1)
    type(Key.ENTER)
    waitVanish("Namehisisare.png")
    #------Assert changes exists---------#
    assert exists(Pattern("ITypeIpateNa.png").similar(0.89))
    keyDown(Key.SHIFT)
    type(Key.TAB)
    keyUp(Key.SHIFT)
    type(Key.ENTER)
    waitVanish("Usethisdialo-4.png")

#create_customfields()