from sikuli import*

def create_task(id):
    type("n", KeyModifier.ALT)
    type("f")
    type("n", KeyModifier.CTRL)
    wait("IZI1IClassif.png")
    paste ("Sikuli Test Task " + str(id))
    type(Key.TAB)
    type(Key.TAB)
    type(Key.TAB)
    type(Key.ENTER)
    paste("Sikuli Test Expense Full Name")
    type(Key.TAB)
    type(Key.TAB)
    type(Key.TAB)
    paste("10")
    type(Key.TAB)
    paste("20")
    type(Key.TAB)
    paste("30")
    type(Key.TAB)
    paste("40")
    type(Key.TAB)
    paste("50")
    type(Key.TAB)
    paste("60")
    type(Key.TAB)
    paste("70")
    type(Key.TAB)
    paste("80")
    type(Key.TAB)
    paste("90")
    type(Key.TAB)
    paste("100")
    type(Key.TAB)
    paste("110")
    type(Key.TAB)
    paste("120")
    type(Key.TAB)
    paste("130")
    type(Key.TAB)
    paste("140")
    type(Key.TAB)
    paste("150")
    type(Key.TAB)
    paste("160")
    type(Key.TAB)
    paste("170")
    type(Key.TAB)
    paste("180")
    type(Key.TAB)
    paste("190")
    type(Key.TAB)
    paste("200")
    type(Key.TAB)
    type(Key.TAB)
    paste("1.5")
    type(Key.TAB)
    type(Key.TAB)
    type(Key.TAB)
    type(Key.TAB)
    paste("Default Sikuli Description")
    wait(Pattern("DefaultSikul.png").similar(0.97))
    type("s", KeyModifier.CTRL)
    waitVanish(Pattern("1351792567535.png").similar(0.98))
    keyDown(Key.CTRL)
    type(Key.F4)
    keyUp(Key.CTRL)