from sikuli import*

def clear_slips():
    type("s", KeyModifier.ALT)
    type("u")
    wait(Pattern("Y0ucanusetfi.png").similar(0.94))
    if exists(Pattern("Youcanusetfi-1.png").similar(0.97)): 
        type(Key.TAB)
        type(Key.TAB)
        type(Key.TAB)
        type(Key.ENTER)
        return
    else:
        type("s", KeyModifier.ALT)
        type(Key.DOWN)
        type(Key.DOWN)
        type(Key.TAB)
        type(Key.DOWN)
        type(Key.TAB)
        type(Key.ENTER)
        wait(.5)
        type("sikuli")
        wait(.5)
        type(Key.F4)
        type(Key.ENTER)
        type("o", KeyModifier.ALT)
        wait(Pattern("SelectionInd-1.png").similar(0.94))
        type("a", KeyModifier.CTRL)
        type(Key.F4)
        wait(.5)
        type("d", KeyModifier.ALT)
        wait(.5)
        type("y")
        type(Key.RIGHT)
        type(Key.ENTER)
        wait("successfully.png")
        type(Key.ENTER)
        wait(.5)
        type(Key.TAB)
        type(Key.TAB)
        type(Key.TAB)
        wait(.5)
        type(Key.ENTER)