def old_TSslip_entry():
    keyDown(Key.CTRL)
    keyDown(Key.SHIFT)
    click("1349207959804.png")
    keyUp(Key.CTRL)
    keyUp(Key.SHIFT)
    wait(.5)
    type("t")
    type(Key.TAB)
    type("s. robertson")
    type(Key.ENTER)
    type(Key.TAB)
    type("sikuli test task")
    type(Key.ENTER)
    type(Key.TAB)
    type("sikuli test client")
    type(Key.ENTER)
    type(Key.TAB)
    type("sikuli test reference")
    type(Key.ENTER)
    type(Key.TAB)
    paste("sikuli extra")
    type(Key.TAB)
    type("sikuli test description and sta ")
    wait(.5)
    paste("Sikuli prompt 1")
    type(Key.TAB)
    type(Key.ENTER)
    wait(.5)
    paste("Sikuliprompt 2")
    type(Key.TAB)
    type(Key.ENTER)
    wait(.5)
    paste("Sikuli prompt 3")
    type(Key.TAB)
    type(Key.ENTER)
    type(Key.TAB)
    type("6/23/2004")
    type(Key.TAB)
    type("6/24/2004")
    type("c")
    click("1349292786849.png")
    click("1349292832471.png")
    type(Key.TAB)
    type(Key.TAB)
    type(Key.TAB)
    type(Key.ENTER)
    type(Key.TAB)
    paste("00:30:00")
    type(Key.TAB)
    """change the below value to test assertion, correct value should be 1:00:00"""
    paste("1:00:00")
    type(Key.TAB)
    """Next line starts Timer"""
    type(Key.SPACE)
    wait(2.2)
    type(Key.SPACE)
    type(Key.TAB)
    type(Key.DOWN)
    wait(.1)
    type(Key.DOWN)
    wait(.1)
    type(Key.DOWN)
    wait(.1)
    type(Key.UP)
    wait(.1)
    type(Key.UP)
    wait(.1)
    type(Key.UP)
    type(Key.TAB)
    """Next line enables and disables Hold"""
    type(Key.SPACE)
    type(Key.SPACE)
    wait(.5)
    type(Key.TAB)
    type(Key.SPACE)
    type(Key.SPACE)
    wait(.5)      
    type(Key.TAB)
    type(Key.DOWN)
    type(Key.DOWN)
    type(Key.UP)
    type(Key.TAB)
    type(Key.DOWN)
    type(Key.TAB)
    type(Key.TAB)
    """Next section begins Markup and Attachments"""
    click("lvlarkuuAdiu.png")
    click("Attachments.png")
    type(Key.TAB)
    paste("5.00")
    type(Key.TAB)
    paste("2.00")
    type(Key.TAB)
    paste("0:15:59")
    click("1349297553370.png")
    click("Starttime.png")
    type(Key.TAB)
    type(Key.TAB)
    type(Key.TAB)
    type(Key.TAB)
    type(Key.ENTER)
    """click("UnUlf-1.png")"""
    wait(.5)
    type("s", KeyModifier.CTRL)
    wait(.5)
    click("MarkuDAdiusl.png")
    click("Attachments-1.png")
    """
    click("22513Value.png")
    if not exists("SlipValueBil.png"): exit(1)
    else: exit(0)
    click("1349459692282.png")"""
    wait(.5)
    keyDown(Key.CTRL)
    type(Key.F4)
    keyUp(Key.CTRL)
    wait(.5)
    click("Sis.png")
    keyDown(Key.CTRL)
    keyDown(Key.SHIFT)
    click("Tin.png")
    keyUp(Key.CTRL)
    keyUp(Key.SHIFT)
    wait(1)
    if not exists("185195994225-1.png"): exit(1)
    else: exit(0)







old_TSslip_entry()    