from sikuli import*
import logging
import os
import subprocess
import logging
reload(logging)
import datetime
import mySettings



def insert_prompt():
    type('i', KeyModifier.ALT)
    wait("1406647585593.png", 30)
    paste('Prompt 1')
    type(Key.ENTER)
    waitVanish("1406647585593.png")
    type('i', KeyModifier.ALT)
    wait("1406647585593.png", 30)
    paste('Prompt 2')
    type(Key.ENTER)
    waitVanish("1406647585593.png")
    type('i', KeyModifier.ALT)
    wait("1406647585593.png", 30)
    paste('Prompt 3')
    type(Key.ENTER)
    waitVanish("1406647585593.png")






def abbreviations():
    type("p", KeyModifier.ALT)
    type("a")
    wait(Pattern("1352152087090.png").similar(0.98), FOREVER)
    type("n", KeyModifier.ALT)
    wait(Pattern("henenteringt.png").similar(0.94))
    paste("STA")
    type(Key.TAB)
    paste("Sikuli %Sikuli 1st prompt% Test %Sikuli 2nd prompt% Abbreviations %Sikuli 3rd prompt%")
    wait(.5)
    type('n', KeyModifier.CTRL)
    wait("1406318580624.png", 30)
    type('k', KeyModifier.ALT)
    paste('ATE')
    type(Key.TAB)
    paste('Abbreviation to Edit')    
    keyDown(Key.SHIFT)
    type(Key.TAB)
    type(Key.TAB)
    type(Key.TAB)
    type(Key.TAB)
    keyUp(Key.SHIFT)
    wait(1)
    type(Key.ENTER)
    wait(1)
    assert exists(Pattern("1406320561116.png").similar(0.93))
    type('o', KeyModifier.CTRL)
    wait("1406320225243.png", 30)
    paste('ATD')
    type(Key.TAB)
    type('a', KeyModifier.CTRL)
    paste('Abbreviation to Delete') 
    keyDown(Key.SHIFT)
    type(Key.TAB)
    type(Key.TAB)
    type(Key.TAB)
    type(Key.TAB)
    keyUp(Key.SHIFT)
    wait(1)
    type(Key.ENTER)
    wait(1)
    assert exists("1406320672782.png")
    type('STA')
    assert exists(Pattern("1406572764670.png").similar(0.96))
    type('o', KeyModifier.ALT)
    wait("1406572829721.png", 30)
    type(Key.PAGE_UP)
    assert exists(Pattern("1406573058538.png").similar(0.93))
    type(Key.PAGE_DOWN)
    assert exists(Pattern("1406573089449.png").similar(0.97))
    type(Key.PAGE_UP, KeyModifier.CTRL)
    assert exists(Pattern("1406573058538.png").similar(0.93))
    type(Key.PAGE_DOWN, KeyModifier.CTRL)
    assert exists(Pattern("1406573089449.png").similar(0.97))
    keyDown(Key.SHIFT)
    type(Key.TAB)
    type(Key.TAB)
    keyUp(Key.SHIFT)
    wait(1)
    type(Key.ENTER)
    waitVanish(Pattern("1406573089449.png").similar(0.97))
    #insert prompt dialog
    type('n', KeyModifier.ALT)
    wait(Pattern("henenteringt.png").similar(0.94))
    paste("PMT")
    insert_prompt()
    keyDown(Key.SHIFT)
    type(Key.TAB)
    type(Key.TAB)
    type(Key.TAB)
    keyUp(Key.SHIFT)
    wait(1)
    type(Key.ENTER)
    waitVanish(Pattern("henenteringt.png").similar(0.94))  
    #Start of testing for Personal Page
    type(Key.F6)
    if exists("1406573695241.png"):
        type(Key.ENTER)
        waitVanish("1406573695241.png")
        wait("1406573745174.png", 30)
        type('n', KeyModifier.ALT)
        paste(os.path.join(r'C:\tssmoketest', Settings.Version, ))
        type(Key.ENTER)
        paste('TSSMOKETEST1.ABR')
        wait(.5)
        type('s', KeyModifier.ALT)
        waitVanish("1406573745174.png")
    assert exists(Pattern("1406580874300.png").similar(0.94))
    type("n", KeyModifier.ALT)
    wait(Pattern("henenteringt.png").similar(0.94))
    paste('PER')
    type(Key.TAB)
    paste('Personal Abbreviations Test')
    type('a', KeyModifier.CTRL)
    type('b', KeyModifier.CTRL)
    assert not exists(Pattern("1406655877255.png").similar(0.97))
    assert exists(Pattern("1406655915709.png").similar(0.98))
    type('b', KeyModifier.CTRL)
    wait(.5)
    type('i', KeyModifier.CTRL)
    assert exists(Pattern("1406656564531.png").similar(0.98))
    type('i', KeyModifier.CTRL)
    wait(.5)
    type('u', KeyModifier.CTRL)
    type(Key.RIGHT)
    assert exists(Pattern("1406656636742.png").similar(0.98))
    type('a', KeyModifier.CTRL)
    wait(.5)
    type('u', KeyModifier.CTRL)   
    #type(Key.DELETE)
    type(Key.RIGHT)
    wait(.5)
    type(Key.INSERT, KeyModifier.ALT)
    wait(.5)
    type(Key.BACKSPACE)
    wait(.5)
    paste('PTITEST')
    type(Key.SPACE)
    assert exists(Pattern("1406661282731.png").similar(0.98))    
    keyDown(Key.SHIFT)
    type(Key.TAB)
    type(Key.TAB)
    type(Key.TAB)
    type(Key.TAB)
    keyUp(Key.SHIFT)
    wait(.5)
    type(Key.ENTER)
    waitVanish(Pattern("henenteringt.png").similar(0.94))
    type('s', KeyModifier.ALT)
    wait("1406573745174.png", 30)
    type('n', KeyModifier.ALT)
    paste('c:')        
    type(Key.ENTER)
    type('n', KeyModifier.ALT)    
    paste(os.path.join(r'C:\tssmoketest', Settings.Version, ))
    type(Key.ENTER)
    paste('TSSMOKETEST2.ABR')
    wait(.5)
    type('s', KeyModifier.ALT)
    if exists("1406662708088.png"):
        type('y')
        waitVanish("1406573745174.png")                                                                                                                                                                                                                                                                                                                                                                                                                   
    #special character option
    type('a', KeyModifier.ALT)
    wait(.5)      
    assert exists(Pattern("1407855586577.png").similar(0.89))
    #switch back to DB tab 
    type(Key.F6) 
    assert exists(Pattern("1406661529020.png").similar(0.96))
    keyDown(Key.SHIFT)
    type(Key.TAB)
    type(Key.TAB)
    type(Key.TAB)
    type(Key.TAB)
    keyUp(Key.SHIFT)
    wait(.5)   
    type('ATD')
    type(Key.DELETE, KeyModifier.CTRL)
    wait("1406320415819.png", 30)
    type('y')
    waitVanish("1406320415819.png")
    assert exists(Pattern("1406663903595.png").similar(0.93))
            
    keyDown(Key.SHIFT)
    type(Key.TAB)
    type(Key.TAB)
    keyUp(Key.SHIFT)
    wait(1)
    type(Key.ENTER)


#abbreviations()