doubleClick("1348678216612.png")
wait("File-2.png")
click("File-3.png")
wait(1)
click("OpenDatabase.png")
wait(1)
find("minps.png")
type("a", KeyModifier.CTRL)
type(Key.BACKSPACE)
type("C:\tsshare\timeslips 2014\Original System DB 2013")
click("Open.png")
doubleClick("DATA01.png")
doubleClick("MAINDB.png")
wheel(WHEEL_DOWN, 7)
click("SRobertson.png")
click("Finish.png")